[project]
name = "flugema"
version = "0.2.7"
description = "A web tool, for Private pilots."
readme = "README.md"
authors = [
    { name = "Xeladaren", email = "xeladaren@pm.me" }
]
requires-python = ">=3.14"
dependencies = ["nicegui", "pywebview", "plotly", "matplotlib", "gpxpy", "argon2-cffi", "drawsvg"]

[project.scripts]
flugema = "flugema:main"

[build-system]
requires = ["uv_build>=0.12.4,<0.13.0"]
build-backend = "uv_build"
